sudo: false
dist: bionic

language: java
jdk:
  - openjdk8
  #- openjdk11 - some dependencies randomly fail with "peer not authenticated"

install: true
script: ./gradlew build

notifications:
  email: false
